config/routes.rb
Rails.application.routes.draw do
  

  resources :blog_entries
  
  get 'static_pages/contact'
  

  

  root 'blog_entries#index'

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
    has_many :blog_entries 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_action :set_blog_entry, only: [:show, :edit, :update, :destroy]

  # GET /blog_entries
  # GET /blog_entries.json
  def index
    @blog_entries = BlogEntry.all
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.json
  def show
  end

  # GET /blog_entries/new
  def new
    @blog_entry = BlogEntry.new
  end

  # GET /blog_entries/1/edit
  def edit
  end

  # POST /blog_entries
  # POST /blog_entries.json
  def create
    @blog_entry = BlogEntry.new(blog_entry_params)

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully created.' }
        format.json { render :show, status: :created, location: @blog_entry }
      else
        format.html { render :new }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_entries/1
  # PATCH/PUT /blog_entries/1.json
  def update
    respond_to do |format|
      if @blog_entry.update(blog_entry_params)
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_entry }
      else
        format.html { render :edit }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.json
  def destroy
    @blog_entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_entries_url, notice: 'Blog entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_entry
      @blog_entry = BlogEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_entry_params
      params.require(:blog_entry).permit(:title, :date, :subtitle, :body, :image_url1, :image_url2, :image_url3, :image_url4)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blog_entries/_form.html.erb
<%= form_for(@blog_entry) do |f| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog_entry from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_entries/edit.html.erb
<h1>Editing Blog Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_entry %> |
<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Entries</h1>


<div class="container-fluid">
  <div class="entry">
    <% @blog_entries.each do |blog_entry|%>
      <div class="complete_entry">
        <h1><%= blog_entry.title %></h1>
        <h3><%= blog_entry.subtitle %></h3>
        <p><%= blog_entry.date %></p>
        <p><%= blog_entry.body %></p>
      </div>



<p><%= link_to 'Show', blog_entry %>
<%= link_to 'Edit', edit_blog_entry_path(blog_entry) %>
<%= link_to 'Destroy', blog_entry, method: :delete, data: { confirm: 'Are you sure?' } %></p>


      
    <% end %>
  </div>
    
      
</div>

<%= link_to 'New Blog entry', new_blog_entry_path %>

app/views/blog_entries/new.html.erb
<h1>New Blog Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="complete_entry">
  <h1>
    <strong>Title:</strong>
    <%= @blog_entry.title %>
  </h1>

  <h3>
    <strong>Subtitle:</strong>
    <%= @blog_entry.subtitle %>
  </h3>
  
  <p>
    <strong>Date:</strong>
    <%= @blog_entry.date %>
  </p>
  
  <p>
    Body:
    <%= @blog_entry.body %>
  </p>

</div>


<%= link_to 'Edit', edit_blog_entry_path(@blog_entry) %> |
<%= link_to 'Back', blog_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Workspace</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Damage and Dolls</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%=link_to"home", blog_entries_path%></li>
      <li><%=link_to"ask for a rant, i've got an opinion", static_pages_contact_path%></li> 
    </ul>
  </div>
</nav>

<%= yield %>

<footer class="footer">
  <div class="container">
    <p class="text-muted">Damage & Dolls blog est 2014</p>
  </div>
</footer>

</body>
</html>

app/views/static_pages/contact.html.erb
<div class="complete_entry">
<h1> danddolls@gmail.com</h1>
<p> let's talk about taking on the patriarchy, with our daughters in tow!</p>
</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>